contentColumnType: string
fieldGroup: 2632ec4e-061b-4415-86a6-3bc53d216f14 # Blog Post Fields
handle: postCategories
instructions: ''
name: 'Post Categories'
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: 'group:ac8d7612-cd0f-476e-b974-6c7df7263a07' # Blog Categories
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
