fieldLayouts:
  80460413-6ab8-4ef4-a63a-9d909d801ec8:
    tabs:
      -
        elements:
          -
            fieldUid: f4506959-1fc0-46e2-af46-1ccd41e2be61 # Site Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: siteInformation
name: 'Site Information'
sortOrder: 1
