enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  8c1d5cb2-1c66-41a5-a83a-be99f27ad039: # Tutorial
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
