enableVersioning: true
handle: blog
name: Blog
propagationMethod: all
siteSettings:
  8c1d5cb2-1c66-41a5-a83a-be99f27ad039: # Tutorial
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry
    uriFormat: 'blog/{slug}'
type: channel
